apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-django-secret
stringData:
  SECRET_KEY: "{{ .Values.web.django.settings.secret_key }}"
  EMAIL_HOST: "{{ .Values.web.django.settings.email_host }}"
  EMAIL_HOST_USER: "{{ .Values.web.django.settings.email_host_user }}"
  EMAIL_HOST_PASSWORD: "{{ .Values.web.django.settings.email_host_password }}"
  DEFAULT_FROM_EMAIL: "{{ .Values.web.django.settings.default_from_email }}"
