# Generated by Django 5.1.2 on 2024-10-28 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kbase', '0004_alter_article_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='created_at',
            new_name='created_date',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='modified_at',
            new_name='modified_date',
        ),
    ]
