# Generated by Django 5.1.2 on 2024-11-06 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kbase', '0006_tags_remove_article_category_article_tags_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tags',
            new_name='Tag',
        ),
    ]
