# Generated by Django 5.1.4 on 2025-01-02 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0012_user_is_verified_alter_group_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_verification_email_sent',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
