# Generated by Django 5.1.2 on 2024-11-11 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kbase', '0007_rename_tags_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='tag',
            field=models.CharField(max_length=25, unique=True),
        ),
    ]
