# Generated by Django 5.1.2 on 2024-11-19 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_remove_user_groups_group_users_alter_group_name'),
        ('kbase', '0008_alter_tag_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='groups_with_edit',
            field=models.ManyToManyField(blank=True, related_name='groups_edit_articles', to='authentication.group'),
        ),
        migrations.AddField(
            model_name='article',
            name='groups_with_view',
            field=models.ManyToManyField(blank=True, related_name='groups_view_articles', to='authentication.group'),
        ),
    ]
